A:
  name: 原点起点
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
B:
  name: 水果店
  position:
    x: 0.75
    y: 0.05
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
C:
  name: 工具间
  position:
    x: -0.4
    y: 1.5
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
D:
  name: 便利店
  position:
    x: 0.75
    y: 1.5
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
E:
  name: 未命名4
  position:
    x: 1.8367345476132753
    y: 0.7013029946525896
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.4027633628210963
    w: 0.915304142659172
F:
  name: 椅子
  position:
    x: 1.6153546566745638
    y: 2.3264033220194626
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.8474569755089905
    w: 0.5308640830392982
